IF OBJECT_ID('dbo.Player', 'U') IS NOT NULL
 DROP TABLE dbo.Player;
GO

CREATE TABLE [dbo].[Player]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Email] NVARCHAR(MAX) NOT NULL, 
    [Name] NVARCHAR(MAX) NOT NULL, 
    [LastUsed] DATETIME,
    [ImageUrl] NVARCHAR(MAX) NOT NULL
)
