CREATE TABLE [dbo].[Character]
(
  [Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PlayerId] INT NOT NULL,
    [Name] VARCHAR(MAX) NOT NULL, 
    [TrueName] VARCHAR(MAX), 
    [Aliases] VARCHAR(MAX), 
    [Species] VARCHAR(MAX), 
    [DamageClass] INT, 
    [Height] VARCHAR(15), 
    [Weight] VARCHAR(15), 
    [Notes] VARCHAR(MAX), 
    [SkinDescription] VARCHAR(MAX), 
    [HairDescription] VARCHAR(MAX), 
    [Description] VARCHAR(MAX), 
    [Birthdate] BIGINT, 
    [XPTotal] FLOAT, 
    [XPBanked] FLOAT, 
    [IsPlayable] BIT NOT NULL,
    [ActionPointMax] INT,
    [ActionPointRecovery] INT,
    [ActionPointAvailable] INT,
    [IsPassedOut] BIT NOT NULL, 
    [VitValue] INT,
    [VitBaseValue] INT,
    [VitPendingHealing] INT,
    [VitPendingDamage] INT,
    [FatValue] INT,
    [FatBaseValue] INT,
    [FatPendingHealing] INT,
    [FatPendingDamage] INT,
    [ImageUrl] VARCHAR(MAX) NOT NULL
)
